### ISSUE TITLE
Unable to access HTTP port when GitLab is run behind port forwarding device

### ISSUE THREAD

**Issue by yabusygin** [yabusygin/ansible-role-gitlab#4]
GitLab instance is run behind a gateway that performs port forwarding from port 8000 to GitLab's port 80. The following configuration is applied:

```yaml
---
gitlab_url: http://gitlab.test:8000
```

When accessing GitLab Web UI via the specified URL connection is reset.

**Comment by yabusygin** [comment]
This happens because bundled Nginx starts listening port 8000 but we have the following settings in `docker-compose.yml`:

```yaml
# ...
services:
  gitlab:
    # ...
    ports:
      - protocol: tcp
        target: 80
        published: 80
# ...
```

Target port specified in Compose file and port listened by Nginx are mismatching.
