### ISSUE TITLE
Missing lstrip_blocks option for template rendering tasks

### ISSUE THREAD

**Issue by yabusygin** [yabusygin/ansible-role-gitlab#6]
Missing `lstrip_blocks` option for template rendering tasks results in ugly config formatting.

**Comment by yabusygin** [comment]
Example of a task with the issue:

```yml
- name: create config file
  template:
    src: gitlab.rb.j2
    dest: /etc/docker-gitlab/gitlab.rb
```

The following should be used instead:

```yml
- name: create config file
  template:
    src: gitlab.rb.j2
    dest: /etc/docker-gitlab/gitlab.rb
    lstrip_blocks: yes
```
