### ISSUE TITLE
It should be posible to specify a custom gitlab.rb config

### ISSUE THREAD

**Issue by yabusygin** [yabusygin/ansible-role-gitlab#68]
Currently, there is no way to configure any GitLab features that are not covered
by a `templates/gitlab.rb.j2` template. To address this issue the following
behavior should be implemented.

If a `gitlab_config` variable is defined, then a custom `gitlab.rb` config file
specified by the variable is used instead of the `templates/gitlab.rb.j2` template.
The `templates/gitlab.rb.j2` template is ignored.

An example playbook:

```yaml
- hosts: gitlab
  tasks:
    - import_role:
        name: yabusygin.gitlab
      vars:
        gitlab_config: path/to/gitlab.rb
```

An example `path/to/gitlab.rb` config file that enables uploading of backups to Amazon S3
storage:

```ruby
external_url 'https://gitlab.example.com'

gitlab_rails['backup_upload_connection'] = {
  'provider' => 'AWS',
  'region' => 'eu-west-1',
  'aws_access_key_id' => 'AKIAKIAKI',
  'aws_secret_access_key' => 'secret123'
}
gitlab_rails['backup_upload_remote_directory'] = 'my.s3.bucket'
```

*Warning.* The above `gitlab.rb` config is provided for example purposes only.
I've just copied it from the [documentation][1] without testing.

[1]: https://docs.gitlab.com/ee/raketasks/backup_restore.html#uploading-backups-to-a-remote-cloud-storage
